# Generated by Django 5.0.6 on 2024-06-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('usercontact', models.CharField(max_length=50)),
                ('useremail', models.CharField(max_length=50)),
                ('userpassword', models.CharField(max_length=50)),
                ('useraddress', models.CharField(max_length=50)),
                ('userphoto', models.FileField(upload_to='Assets/UserPhoto')),
            ],
        ),
    ]
