# Generated by Django 5.0.6 on 2024-06-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='tbl_user',
        ),
    ]
