# Generated by Django 5.0.6 on 2024-06-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_admin'),
        ('Guest', '0003_alter_tbl_user_userphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50)),
                ('shopcontact', models.CharField(max_length=50)),
                ('shopemail', models.CharField(max_length=50)),
                ('shoppassword', models.CharField(max_length=50)),
                ('shopaddress', models.CharField(max_length=50)),
                ('shopphoto', models.FileField(upload_to='Assets/ShopPhoto/')),
                ('shopproof', models.FileField(upload_to='Assets/ShopProof/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
